{
 "title": "IP Traffic Monitor",
 "description": "https://github.com/lyh543/ip_traffic_monitor_cli",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "Country",
    "query": {
     "query": "label_values(ip_traffic_tx_bytes_total,country)"
    }
   },
   {
    "name": "city",
    "label": "City",
    "query": {
     "query": "label_values(ip_traffic_tx_bytes_total{country=\"$country\"},city)"
    }
   },
   { "name": "top_k", "label": "Top", "query": "10,20,50,100,200,500,1000" }
  ]
 },
 "panels": [
  { "title": "TX (Upload Traffic) Increase", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Upload Traffic Increase",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ip_traffic_tx_bytes_total{country=~\"$country\", city=~\"$city\"}) - sum(ip_traffic_tx_bytes_total{country=~\"$country\", city=~\"$city\"} @ ${__from:date:seconds})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload Traffic Increase (by country)",
   "type": "table",
   "gridPos": { "h": 8, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($top_k, sum by (country) ((ip_traffic_tx_bytes_total{country=~\"$country\", city=~\"$city\"}) - (ip_traffic_tx_bytes_total{country=~\"$country\", city=~\"$city\"} @ ${__from:date:seconds} or ip_traffic_tx_bytes_total{country=~\"$country\", city=~\"$city\"} * 0)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload Traffic Increase (by city)",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($top_k, sum by (country, city) ((ip_traffic_tx_bytes_total{country=~\"$country\", city=~\"$city\"}) - (ip_traffic_tx_bytes_total{country=~\"$country\", city=~\"$city\"} @ ${__from:date:seconds} or ip_traffic_tx_bytes_total{country=~\"$country\", city=~\"$city\"} * 0)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload Traffic Increase (by ip)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($top_k, (ip_traffic_tx_bytes_total{country=~\"$country\", city=~\"$city\"} - (ip_traffic_tx_bytes_total{country=~\"$country\", city=~\"$city\"} @ ${__from:date:seconds} or ip_traffic_tx_bytes_total{country=~\"$country\", city=~\"$city\"} * 0) > 0))",
     "legendFormat": "{{remote_ip}}({{country}}, {{city}})"
    }
   ]
  },
  { "title": "RX (Download Traffic) Increase", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Download Traffic Increase",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ip_traffic_rx_bytes_total{country=~\"$country\", city=~\"$city\"}) - sum(ip_traffic_rx_bytes_total{country=~\"$country\", city=~\"$city\"} @ ${__from:date:seconds})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Download Traffic Increase (by country)",
   "type": "table",
   "gridPos": { "h": 8, "w": 3, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($top_k, sum by (country) ((ip_traffic_rx_bytes_total{country=~\"$country\", city=~\"$city\"}) - (ip_traffic_rx_bytes_total{country=~\"$country\", city=~\"$city\"} @ ${__from:date:seconds} or ip_traffic_rx_bytes_total{country=~\"$country\", city=~\"$city\"} * 0)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Download Traffic Increase (by city)",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($top_k, sum by (country, city) ((ip_traffic_rx_bytes_total{country=~\"$country\", city=~\"$city\"}) - (ip_traffic_rx_bytes_total{country=~\"$country\", city=~\"$city\"} @ ${__from:date:seconds} or ip_traffic_rx_bytes_total{country=~\"$country\", city=~\"$city\"} * 0)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Download Traffic Increase (by ip)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($top_k, (ip_traffic_rx_bytes_total{country=~\"$country\", city=~\"$city\"} - (ip_traffic_rx_bytes_total{country=~\"$country\", city=~\"$city\"} @ ${__from:date:seconds} or ip_traffic_rx_bytes_total{country=~\"$country\", city=~\"$city\"} * 0) > 0))",
     "legendFormat": "{{remote_ip}}({{country}}, {{city}})"
    }
   ]
  },
  {
   "title": "TX (Upload Traffic) Total",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Upload Total Traffic",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ip_traffic_tx_bytes_total{country=~\"$country\", city=~\"$city\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Upload Total Traffic (by ip)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk($top_k, ip_traffic_tx_bytes_total{country=~\"$country\", city=~\"$city\"}>0)",
       "legendFormat": "{{remote_ip}}({{country}}, {{city}})"
      }
     ]
    }
   ]
  },
  {
   "title": "RX (Download Traffic) Total",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Download Total Traffic",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ip_traffic_rx_bytes_total{country=~\"$country\", city=~\"$city\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Download Total Traffic (by ip)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk($top_k, ip_traffic_rx_bytes_total{country=~\"$country\", city=~\"$city\"}>0)",
       "legendFormat": "{{remote_ip}}({{country}}, {{city}})"
      }
     ]
    }
   ]
  }
 ]
}